added types for project with TypeScript
Roman375/axels-task pull request #5
Opened 2021-03-05 14:51 UTC by Roman375

2021-03-05 14:57 UTC, Roman375 commented on src/types/employeesType.ts
> +}
Виправив в наступному коміті

2021-03-05 14:57 UTC, Roman375 commented on src/types/overviewsType.ts
> +}
Виправив в наступному коміті

2021-03-05 19:17 UTC, mike-gusiev requested changes

2021-03-05 19:17 UTC, mike-gusiev commented on src/App.tsx
> +const mapStateToPrors = (state: any) => {
используй краткую форму без return, нужно избавиться от всех any в проекте

2021-03-05 19:17 UTC, mike-gusiev commented on src/api/api.ts
> +  getOverviews(employeeName: string): any{
не хватает пробела перед открывающейся скобкой, избавишься от any

2021-03-09 10:39 UTC, mike-gusiev approved these changes

2021-03-09 10:40 UTC, merged